# Site settings
title: Get Outta The Box - Antoine Butler
email: hi@getouttathebox.com
description: > # this means to ignore newlines until "baseurl:"
  The chronicles of a wanderlusting, remote worker and fitnesses junky. Sharing
  philosophical musings on my never ending search for work-life balance.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://getouttathebox.com" # the base hostname & protocol for your site
twitter_username: aebsr
github_username:  aebsr
instagram_username:  aebsr

# Build settings
markdown: kramdown
